### PR TITLE
Corrected color theme. 

### PR DESCRIPTION
**Pull request by benreckas**
### Summary of solution:
Fixed broken links and added easy to read tables of values.

### CODE REVIEW

**Comment by motosharpley** [comment]
Looks good thank you!

**Comment by jp853** [comment]
I like the green theme!

**Comment by alicepalazzolo** [comment]
Color Scheme to go with new NAVI Logo -- Looking for some feedback
color_theme_blue_with_accent
color_theme_multi
color_theme_multi2
colorthememonoblue

**Comment by motosharpley** [comment]
@TheDevPath/grow-with-google let's give some feedback on your favorite color scheme

**Comment by motosharpley** [comment]
my top two votes are
1- first scheme
2 - second scheme

**Comment by alicepalazzolo** [comment]
I am personally leaning toward the first one-- I don't think a green tone is needed but the pop of color is a good accent when needed.

**Comment by sonalikatara** [comment]
I like the first one too

**Comment by jkwening** [comment]
ditto on the first

**Comment by tanyagupta** [comment]
The first one

**Comment by shiolovesgod** [comment]
Im a fan of the contrast with the green

**Comment by desdemonhu** [comment]
First is my favorite too

**Pull request merged**
