### PR TITLE
Create static landing page

### PR DESCRIPTION
**Pull request by pjdmatts**
### Summary of solution:
1. Basic landing page based on mock ups and color scheme
2. Index.html, reset.css and style.css
3. Readme.md contains a to-do

### Can this issue be closed?
Not yet, no. We will want to add the logo and make the page suitable for both mobile and desktop - right now it is based on the mobile mock up.

### CODE REVIEW

**Comment by motosharpley** [comment]
I will work on finding some examples of how we can transform this to mimic the download page for a native or desktop app and how we can emulate the native experience on phones.

**Comment by motosharpley** [comment]
This is one of the things we need to incorporate https://developers.google.com/web/fundamentals/app-install-banners/

**Comment by motosharpley** [comment]
Here is a tutorial which walks through the install banner process and is actually a pretty good explanation on PWAs and service workers in general https://youtu.be/I3jTvWj8JrQ

**Comment by pjdmatts** [comment]
Thanks - I will check it out tonight/tomorrow.

**Comment by motosharpley** [comment]
I'm going to close this for now and we can reopen when we get further along on this issue.

**Pull request closed without merging**
