### PR TITLE
Iss. 10 - Create an app Color Scheme. 

### PR DESCRIPTION
**Pull request by benreckas**

### CODE REVIEW

**Comment by tophergates** [comment]
404 error when visiting provided links:

> Sorry we can't find the page you're looking for, either it doesn't exist or you do not have permissions to view it.

Suggest removing external links and outlining brand color requirements inside the doc, such as:

| | RGB | HEX | HSL |
| --- | --- | ---| --- |
| **Primary** | rgb(xx, xx, xx) | #xxxxxx | hsla(xx, xx%, xx%, 1) |
| **Primary Light** | rgb(xx, xx, xx) | #xxxxxx | hsla(xx, xx%, xx%, 1) |
| **Primary Dark** | rgb(xx, xx, xx) | #xxxxxx | hsla(xx, xx%, xx%, 1) |
| **Accent 1** | rgb(xx, xx, xx) | #xxxxxx | hsla(xx, xx%, xx%, 1) |
| **Accent 2** | rgb(xx, xx, xx) | #xxxxxx | hsla(xx, xx%, xx%, 1) |
| **Typography Light** | rgb(xx, xx, xx) | #xxxxxx | hsla(xx, xx%, xx%, 1) |
| **Typography Dark** | rgb(xx, xx, xx) | #xxxxxx | hsla(xx, xx%, xx%, 1) |

**Comment by benreckas** [comment]
You can go ahead an delete this PR. Sorry for the broken link I checked it on my end and it worked. Must be specific to my account since I'm logged in. I added color values to a table as requested.

**Comment by benreckas** [comment]
The new PR will come from a freshly named branch. :)

**Comment by motosharpley** [comment]
No worries It happens to all of us. That's what the review process is for.
Thank you!

**Pull request closed without merging**
